export const extractTitle = (titre: string) =>
  titre
    .replace(/fin intro bends/gim, '')
    .replace(/intro [0-9]/gim, '')
    .replace(/intro/gim, '')
    .replace(/[b|B]end[ |s]/gm, '')
    .replace(/arp[è|e]ge[ |s]/gim, '')
    .replace(/[v|V]ibrato/gm, '')
    .replace(/^électrique/gim, '')
    .replace(/partie II/gim, '')
    .replace(/(^1ere|^1er|^2ème|^3ème|4ème|5ème) partie/gim, '')
    .replace(/^1ere|^1er|^2ème|^3ème|4ème|5ème/gim, '')
    .replace(/[r|R]alenti/gm, '')
    .replace(/cover rythmique/gim, '')
    .replace(/d[é|e]tail[ |s] rythmique[ |s]/gim, '')
    .replace(/rythmique avancée/gim, '')
    .replace(/rythmique funky initiation/gim, '')
    .replace(/rythmique originale/gim, '')
    .replace(/rythmique [0-9]/gim, '')
    .replace(/[r|R]ythmique/gm, '')
    .replace(/riff \+ pont/gim, '')
    .replace(/pont pré/gim, '')
    .replace(/le pont/gim, '')
    .replace(/pont \+ solo/gim, '')
    .replace(/liaison pont/gim, '')
    .replace(/pont/gim, '')
    .replace(/riff [0-9]/gim, '')
    .replace(/riff d[é|e]butant/gim, '')
    .replace(/riff expert/gim, '')
    .replace(/riff interm[é|e]diaire/gim, '')
    .replace(/riff principal/gim, '')
    .replace(/riff/gim, '')
    .replace(/[a|A]ccords/gm, '')
    .replace(/solo acoustique/gim, '')
    .replace(/solo couplet/gim, '')
    .replace(/solo fin/gim, '')
    .replace(/solo style/gim, '')
    .replace(/solo type/gim, '')
    .replace(/solo [0-9]/gim, '')
    .replace(/exemple de solo/gim, '')
    .replace(/transition vers solo/gim, '')
    .replace(/solo i/gim, '')
    .replace(/solo/gim, '')
    .replace(/[p|P]art [0-9] fin/gm, '')
    .replace(/part[0-9]/gim, '')
    .replace(/part [0-9]/gim, '')
    .replace(/part i/gim, '')
    .replace(/[s|S]ortie refrain/gm, '')
    .replace(/refrain [0-9]/gim, '')
    .replace(/refrain/gim, '')
    .replace(/[g|G]ammes/gm, '')
    .replace(/[l|L]icks/gm, '')
    .replace(/[l|L]ick/gm, '')
    .replace(/[p|P]artie[0-9]/gm, '')
    .replace(/[p|P]artie [0-9]/gm, '')
    .replace(/[s|S]ortie du/gm, '')
    .replace(/[c|C]ouplet/gm, '')
    .replace(/[b|B]loc [0-9]/gm, '')
    .replace(/[f|F]in [o|O]utro/gm, '')
    .replace(/1er [o|O]utro/gm, '')
    .replace(/[o|O]utro/gm, '')
    .replace(/thème folk/gim, '')
    .replace(/thème/gim, '')
    .replace(/theme/gim, '')
    .replace(/structure/gim, '')
    .replace(/penta/gim, '')
    .replace(/explications/gim, '')
    .replace(/variantes/gim, '')
    .replace(/modulations/gim, '')
    .replace(/etche/gim, '')
    .replace(/question réponse/gim, '')
    .replace(/technique plaqué/gim, '')
    .trim()
    .toLowerCase();
